### ISSUE TITLE
Missing curl.cmxs

### ISSUE THREAD

**Issue by colin-gd** [ygrek/ocurl#24]
I've written a library that uses ocurl. This lib used in an ocsigen project as well. When running  the server byte code everything runs well. However the native version doesn't compile. The error message is the following : 
`ocsigenserver.opt: ocsigen:main: Fatal - While loading ~/.opam/4.04.0/lib/curl/curl.cmxs: cannot find file ~/.opam/4.04.0/lib/curl/curl.cmxs in search path`

My guess is that the curl findlib package doesn't include the a curl.cmxs file. This file should be used for dynamic linking in native compilation. I don't know if this is possible, but it would be nice to have a fix for that. I'm not familiar with msvc so I haven't tried to write a patch.

**Comment by ygrek** [comment]
Please see cmxs branch in this repo.
I never used cmxs so not sure if result is correct (esp. curl_lwt.cmxs) and how the dependencies are managed, but produces files seem to have all required symbols and can be dynlink-loaded.

**Comment by colin-gd** [comment]
Cool! Well, I haven't checked extensively but it does seem to work! Thanks :) 👍

**Comment by ygrek** [comment]
fixed b56ce34
