### ISSUE TITLE
curlDebugType not up-to-date, may lead to segfault

### ISSUE THREAD

**Issue by nojb** [ygrek/ocurl#25]
It is missing the cases `CURLINFO_SSL_DATA_IN` and `CURLINFO_SSL_DATA_OUT` and the conversion in `curl-helper.c` (function `cb_DEBUGFUNCTION`) assumes the OCaml constructors correspond exactly with the C enum (see [here](https://github.com/ygrek/ocurl/blob/master/curl-helper.c#L1051) in current master).

**Comment by ygrek** [comment]
Thanks, there was another potential segfaul in same function %)
