### ISSUE TITLE
Curl_lwt.set_debug possibly broken under Windows

### ISSUE THREAD

**Issue by alainfrisch** [ygrek/ocurl#27]
Curl_lwt defines:

````ocaml
let int_of_fd : Unix.file_descr -> int = Obj.magic
````

which is unsafe under Windows (Unix.file_descr being a custom block).  Luckily, this is only used in debug mode, and only for printing the resulting integer.

**Comment by ygrek** [comment]
Thanks for report. Probably can be dropped now, curl_lwt seems to work fine, so no big need to keep debug knobs.
