### ISSUE TITLE
Expose error code if caml_curl_multi_add_handle fails

### ISSUE THREAD

**Issue by dwwoelfel** [ygrek/ocurl#41]
I'm seeing occasional errors when I add an easy handle to the multi interface (with `Curl.Multi.add`). 

The stack trace doesn't give too much information, just `Failure caml_curl_multi_add_handle Raised by primitive operation at Curl in file "curl.ml" (inlined), line 1369`, which is raised at this line [`caml_curl_multi_add_handle`](https://github.com/ygrek/ocurl/blob/70618aa064566d44a99e13bf78ad15131e2ab7d6/curl-helper.c#L4177).

There might be some useful debug information for us in the error code returned by `curl_multi_add_handle`, but right now that error code is not exposed.

Would you be open to exposing that error somehow?

A couple of ideas for how to expose it:

1. Add a `get_last_error` function to `Curl.Multi` that returns an optional error code if there was an error
2. Implement a custom OCaml exception function as in https://ocaml.org/manual/intfc.html#ss:c-register-exn 

I'd be happy to try to implement it if you can give me some direction on how you'd like to see it implemented.

**Comment by ygrek** [comment]
Try git master.
General improvement could be turning `Multi.Error of string (* CURLMcode string *)` into `Multi.Error of string (* function name *) * CURLMcode`

**Comment by dwwoelfel** [comment]
Thanks! Master is working for me.

**Comment by ygrek** [comment]
added Multi.CError and covered all functions in 2e3313712f167738df228b3e276bc24df27d9324
