### ISSUE TITLE
New release after bug fixes have been merged?

### ISSUE THREAD

**Issue by lindig** [ygrek/ocurl#68]
Recent commits fix bugs building on CentOS. While I can work with the current untagged version, would you consider releasing the current version?

**Comment by ygrek** [comment]
can you confirm it builds on CentOS 7? ref #65 
duplicate #66

**Comment by lindig** [comment]
I'm not using a vanilla CentOS 7 but managed to build on a CentOS 7 derived system and believe recent commits addressed earlier problems.
